name       = "forbenchmark"
version    = "VERSION"
author     = "Seyed Ali Ghasemi"
maintainer = "info@gha3mi.com"
copyright  = "Copyright 2023, Seyed Ali Ghasemi"
license    = "LICENSE"

[build]
auto-executables = false
auto-tests       = false
auto-examples    = false
module-naming    = false

[install]
library = false

[fortran]
implicit-typing   = false
implicit-external = false
source-form       = "free"

[dependencies]
kinds   = {git="https://github.com/gha3mi/kinds.git"}
fortime = {git="https://github.com/gha3mi/fortime.git"}
FACE    = {git="https://github.com/szaghi/FACE.git"}
formatmul = {git="https://github.com/gha3mi/formatmul.git", branch = "dev"}
fordot = {git="https://github.com/gha3mi/fordot.git"}

[preprocess]
[preprocess.cpp]

[[example]]
name       = "demo"
source-dir = "example"
main       = "demo.f90"


[[test]]
name       = "dot"
source-dir = "benchmarks/dot"
main       = "dot.f90"

[[test]]
name       = "dot_co"
source-dir = "benchmarks/dot"
main       = "dot_co.f90"

[[test]]
name       = "matmul_matmat"
source-dir = "benchmarks/matmul"
main       = "matmul_matmat.f90"

[[test]]
name       = "matmul_matmat_co"
source-dir = "benchmarks/matmul"
main       = "matmul_matmat_co.f90"

[[test]]
name       = "matmul_matvec"
source-dir = "benchmarks/matmul"
main       = "matmul_matvec.f90"

[[test]]
name       = "matmul_matvec_co"
source-dir = "benchmarks/matmul"
main       = "matmul_matvec_co.f90"