print_message – ForBenchmark
print_message Subroutine
Seyed Ali Ghasemi
14 statements
Source File
private subroutine print_message(condition, message)
Uses
face
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: condition
character(len=*), intent(in) :: message
Calls
Called by
Source Code
   subroutine print_message(condition, message)
      use face
      logical, intent(in) :: condition
      character(*), intent(in) :: message
      integer  :: lm
      character(len=20) :: fmt
      lm = 55-len_trim(message)
      write(fmt,'(a,g0,a)') '(a,a',lm,',a)'
      if (condition) then
         print(fmt), message, colorize('passed.', color_fg='green')
      else
         print(fmt), message, colorize('failed.', color_fg='red')
      end if
   end subroutine print_message
Call graph
print_message calls colorize
unit_test_compare_i1 calls print_message
unit_test_compare_r1 calls print_message
unit_test_r0 calls print_message
unit_test_r1 calls print_message
unit_test_r2 calls print_message
unit_test calls unit_test_compare_i1, unit_test_compare_r1, unit_test_r0, unit_test_r1, unit_test_r2