unit_test_compare_r1 – ForBenchmark
unit_test_compare_r1 Subroutine
Seyed Ali Ghasemi
12 statements
Source File
private subroutine unit_test_compare_r1(u, v, message)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:) :: u
real(kind=rk), intent(in), dimension(:) :: v
character(len=*), intent(in) :: message
Calls
Called by
Source Code
   subroutine unit_test_compare_r1(u, v, message)
      real(rk), intent(in), dimension(:) :: u, v
      character(*), intent(in) :: message
      logical :: condition
      integer :: lm
      character(len=20) :: fmt
      real(rk) :: rel_err
      lm = 46-len_trim(message)
      write(fmt,'(a,g0,a)') '(a,a',lm,',a)'
      condition = any(u==v)
      call print_message(condition , message)
   end subroutine unit_test_compare_r1
Call graph
unit_test_compare_r1 calls print_message
print_message calls colorize
unit_test calls unit_test_compare_r1