unit_test – ForBenchmark
unit_test Interface
7 statements
Source File
public interface unit_test
Calls
Module Procedures
private subroutine unit_test_r0(res, expected, tol, message)
Author
Seyed Ali Ghasemi
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: res
real(kind=rk), intent(in) :: expected
real(kind=rk), intent(in) :: tol
character(len=*), intent(in) :: message
private subroutine unit_test_r1(res, expected, tol, message)
Author
Seyed Ali Ghasemi
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:) :: res
real(kind=rk), intent(in), dimension(:) :: expected
real(kind=rk), intent(in) :: tol
character(len=*), intent(in) :: message
private subroutine unit_test_r2(res, expected, tol, message)
Author
Seyed Ali Ghasemi
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:,:) :: res
real(kind=rk), intent(in), dimension(:,:) :: expected
real(kind=rk), intent(in) :: tol
character(len=*), intent(in) :: message
private subroutine unit_test_compare_r1(u, v, message)
Author
Seyed Ali Ghasemi
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:) :: u
real(kind=rk), intent(in), dimension(:) :: v
character(len=*), intent(in) :: message
private subroutine unit_test_compare_i1(u, v, message)
Author
Seyed Ali Ghasemi
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:) :: u
integer, intent(in), dimension(:) :: v
character(len=*), intent(in) :: message
Call graph
unit_test calls unit_test_compare_i1, unit_test_compare_r1, unit_test_r0, unit_test_r1, unit_test_r2
unit_test_compare_i1 calls print_message
unit_test_compare_r1 calls print_message
unit_test_r0 calls print_message
unit_test_r1 calls print_message
unit_test_r2 calls print_message
print_message calls colorize