name: benchmark_dot
on: [push]
jobs:

  Build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        toolchain:
          - {compiler: gcc}
          - {compiler: intel}
          - {compiler: intel-classic}
          - {compiler: nvidia-hpc}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Fortran Package Manager (fpm)
      uses: fortran-lang/setup-fpm@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install LAPACK and BLAS
      run: sudo apt-get install -y libblas-dev liblapack-dev

    - name: Setup Fortran Compiler
      uses: fortran-lang/setup-fortran@main
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}

    - name: dot benchmark
      run: fpm @benchmark-dot-${{env.FC}}
      env:
        FC: ${{ steps.setup-fortran.outputs.fc }}

    - name: Install Python dependencies
      run: |
        python -m pip install pandas matplotlib

    - name: Results
      run: |
        cd benchmarks/dot && python results/export.py dot_${{env.FC}}.data && cd ../..
      env:
        FC: ${{ steps.setup-fortran.outputs.fc }}

    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FC: ${{ steps.setup-fortran.outputs.fc }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git switch -c results-${{env.FC}}
        git add benchmarks/dot/results/dot_${{env.FC}}*.png
        git add benchmarks/dot/results/dot_${{env.FC}}*.html
        git commit -m "Update results ${{env.FC}}"
        git push -u origin results-${{env.FC}}
        gh pr create -B main -H results --title "Update results-${{env.FC}}" --body ""
