name: test
on: [push]
jobs:

  Build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        toolchain:
          - {compiler: gcc}
          - {compiler: intel}
          - {compiler: intel-classic}
          - {compiler: nvidia-hpc}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Fortran Package Manager (fpm)
      uses: fortran-lang/setup-fpm@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Fortran Compiler
      uses: fortran-lang/setup-fortran@main
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}

    - name: Run demo (Debug)
      run: fpm run --example demo --profile debug --compiler ${{ env.FC}}
      env:
        FC: ${{ steps.setup-fortran.outputs.fc }}

    - name: Run demo (Release)
      run: fpm run --example demo --profile release --compiler ${{ env.FC}}
      env:
        FC: ${{ steps.setup-fortran.outputs.fc }}

    - name: Install Python dependencies
      run: |
        python -m pip install pandas matplotlib

    - name: Plot results
      run: python results/export.py demo.data